### ISSUE TITLE
Inputs/labels

### ISSUE THREAD

**Issue by guoyanb** [thuxugang/opus_tass#1]
The paper is very interesting and inspiring, and I'm quite interested in this work. When I conducted some experiments for protein structure by using "train.py", I met the problem without the "inputs" and "labels". I could not find the data from the link "https://pan.baidu.com/share/init?surl=L6w_qBIKvleO2uFr1Ekevw". Could you kindly release the processed data for the protein structure? Thanks a lot!
![inputs](https://user-images.githubusercontent.com/39645139/100603968-db979500-3340-11eb-9fa7-f41ff62daf63.png)

**Comment by thuxugang** [comment]
Thanks for your interest and sorry for the misleading~
All the xxx.inputs, xxx.labels and xxx.labels_mask files can be found in the corresponding folders (Train / Val / etc), you can simply replace the above two paths with "your_path\opus_tass_datasets\Train"~

**Comment by guoyanb** [comment]
> Thanks for your interest and sorry for the misleading~
> All the xxx.inputs, xxx.labels and xxx.labels_mask files can be found in the corresponding folders (Train / Val / etc), you can simply replace the above two paths with "your_path\opus_tass_datasets\Train"~

Thanks!

**Comment by guoyanb** [comment]
Hello! When I evaluated the model, I met the same problem as the above, and there do not exist inputs and labels in "CAMEO93 & CASP&TEST2016 & TEST2018 ".  I found the ".dssp/.opus" in the TEST2016 & TEST2018 and found the "angles/ .ss" in CAMEO93 & CASP. The process of codes is same for train, val and test set.  What should I do ? Thanks a lot!

**Comment by thuxugang** [comment]
For evaluation, please use inference.py instead :）

**Comment by thuxugang** [comment]
xxx.inputs, xxx.labels and xxx.labels_mask are the formated files for traning,  xxx.dssp, xxx.angles and xxx.ss are the native results~

**Comment by guoyanb** [comment]
Thanks.

> xxx.inputs, xxx.labels and xxx.labels_mask are the formated files for traning, xxx.dssp, xxx.angles and xxx.ss are the native results~
